
//get categories
export const FETCH_CATEGORIES_START = "FETCH_CATEGORIES_START";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAIL = "FETCH_CATEGORIES_FAIL";

//get customer profile
export const FETCH_CUSTOMER_PROFILE_START = "FETCH_CUSTOMER_PROFILE_START";
export const FETCH_CUSTOMER_PROFILE_SUCCESS = "FETCH_CUSTOMER_PROFILE_SUCCESS";
export const FETCH_CUSTOMER_PROFILE_FAIL = "FETCH_CUSTOMER_PROFILE_FAIL";

//get customer address
export const FETCH_CUSTOMER_ADDRESS_START = "FETCH_CUSTOMER_ADDRESS_START";
export const FETCH_CUSTOMER_ADDRESS_SUCCESS = "FETCH_CUSTOMER_ADDRESS_SUCCESS";
export const FETCH_CUSTOMER_ADDRESS_FAIL = "FETCH_CUSTOMER_ADDRESS_FAIL";

//delete customer address
export const DELETE_CUSTOMER_ADDRESS_START = "DELETE_CUSTOMER_ADDRESS_START";
export const DELETE_CUSTOMER_ADDRESS_SUCCESS = "DELETE_CUSTOMER_ADDRESS_SUCCESS";
export const DELETE_CUSTOMER_ADDRESS_FAIL = "DELETE_CUSTOMER_ADDRESS_FAIL";

//update customer address
export const UPDATE_CUSTOMER_ADDRESS_START = "UPDATE_CUSTOMER_ADDRESS_START";
export const UPDATE_CUSTOMER_ADDRESS_SUCCESS = "UPDATE_CUSTOMER_ADDRESS_SUCCESS";
export const UPDATE_CUSTOMER_ADDRESS_FAIL = "UPDATE_CUSTOMER_ADDRESS_FAIL";

//add customer address
export const ADD_CUSTOMER_ADDRESS_START = "ADD_CUSTOMER_ADDRESS_START";
export const ADD_CUSTOMER_ADDRESS_SUCCESS = "ADD_CUSTOMER_ADDRESS_SUCCESS";
export const ADD_CUSTOMER_ADDRESS_FAIL = "ADD_CUSTOMER_ADDRESS_FAIL";

//get seller profile
export const FETCH_SELLER_PROFILE_START = "FETCH_SELLER_PROFILE_START";
export const FETCH_SELLER_PROFILE_SUCCESS = "FETCH_SELLER_PROFILE_SUCCESS";
export const FETCH_SELLER_PROFILE_FAIL = "FETCH_SELLER_PROFILE_FAIL";

//update seller address
export const UPDATE_SELLER_ADDRESS_START = "UPDATE_SELLER_ADDRESS_START";
export const UPDATE_SELLER_ADDRESS_SUCCESS = "UPDATE_SELLER_ADDRESS_SUCCESS";
export const UPDATE_SELLER_ADDRESS_FAIL = "UPDATE_SELLER_ADDRESS_FAIL";


//get categoryById
export const FETCH_CATEGORIESBYID_START = "FETCH_CATEGORIESBYID_START";
export const FETCH_CATEGORIESBYID_SUCCESS = "FETCH_CATEGORIESBYID_SUCCESS";
export const FETCH_CATEGORIESBYID_FAIL = "FETCH_CATEGORIESBYID_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";

export const REDIRECT_PATH = "REDIRECT_PATH"

//register seller
export const ADD_SELLER_INFO = "ADD_SELLER_INFO"
export const SELLER_REGISTER_SUCCESS = "SELLER_REGISTER_SUCCESS"
export const SELLER_REGISTER_FAIL = "SELLER_REGISTER_FAIL"
export const SELLER_REGISTER_START = "SELLER_REGISTER_START"

//activate product
export const ACTIVATE_PRODUCT_START = "ACTIVATE_PRODUCT_START";
export const ACTIVATE_PRODUCT_SUCCESS = "ACTIVATE_PRODUCT_SUCCESS";
export const ACTIVATE_PRODUCT_FAIL = "ACTIVATE_PRODUCT_FAIL";

//deActivate product
export const DEACTIVATE_PRODUCT_START = "DEACTIVATE_PRODUCT_START";
export const DEACTIVATE_PRODUCT_SUCCESS = "DEACTIVATE_PRODUCT_SUCCESS";
export const DEACTIVATE_PRODUCT_FAIL = "DEACTIVATE_PRODUCT_FAIL";


